-- 코드를 입력하세요
# USED_GOODS_BOARD(게시판정보), USED_GOODS_REPLY(첨푸파일정보)
# 2022년 10월에 작성된 게시글 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 댓글 내용, 댓글 작성일
SELECT B.TITLE,B.BOARD_ID,
    R.REPLY_ID,R.WRITER_ID,R.CONTENTS,
    DATE_FORMAT(R.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS B INNER JOIN USED_GOODS_REPLY AS R 
    ON B.BOARD_ID = R.BOARD_ID
WHERE DATE_FORMAT(B.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;