-- 코드를 작성해주세요
SELECT D.DEPT_ID,DEPT_NAME_EN,AVG_SAL
FROM HR_DEPARTMENT D INNER JOIN(
            SELECT D.DEPT_ID,ROUND(AVG(SAL),0) AS AVG_SAL
            FROM HR_DEPARTMENT D INNER JOIN HR_EMPLOYEES E ON D.DEPT_ID = E.DEPT_ID
            GROUP BY D.DEPT_ID) SUB 
        ON D.DEPT_ID = SUB.DEPT_ID
ORDER BY AVG_SAL DESC;
